### ISSUE TITLE
BUG: `flux::scan` broken

### ISSUE THREAD

**Issue by codereport** [tcbrindle/flux#152]
Hey @tcbrindle, 

There is an issue with the `flux::scan` function. It seems as if you are initializing the state to zero, instead of applying the binary operation to the first two elements. It means anything that doesn't have 0 as the "identity" element will break. https://flux.godbolt.org/z/8YK6aErh5

```cpp
auto iota_scan(int n, auto f) {
    return flux::iota(1, n + 1).scan(f).template to<std::vector>();
}

int main() {
    fmt::print("{}\n", iota_scan(5, std::plus{}));        // ✅ [1, 3, 6, 10, 15]
    fmt::print("{}\n", iota_scan(5, std::multiplies{}));  // ❌ [0, 0, 0, 0, 0]
    fmt::print("{}\n", iota_scan(5, std::ranges::max));   // ✅ [1, 2, 3, 4, 5]
    fmt::print("{}\n", iota_scan(5, std::ranges::min));   // ❌ [0, 0, 0, 0, 0]
}
```
Technically the max scan would break as well if you had negative numbers.

**Comment by tcbrindle** [comment]
Hey Conor, thanks for the bug report. In this case however, it's not a bug (as such), but maybe something I need to be more clear about :)

The `flux::scan` adaptor takes a binary function and an optional initial value -- if the latter is not supplied, it defaults to a default-constructed object of the sequence's value type, which is `0` in this case.

If you don't want to use an initial value, there's `scan_first()` which applies the function to the first two elements of the sequence and goes from there. If you use that, it works as expected:

```cpp
auto iota_scan(int n, auto f) {
    return flux::iota(1, n + 1).scan_first(f).template to<std::vector>();
}

int main() {
    fmt::print("{}\n", iota_scan(5, std::plus{}));        // ✅ [1, 3, 6, 10, 15]
    fmt::print("{}\n", iota_scan(5, std::multiplies{}));  // ✅ [1, 2, 6, 24, 120]
    fmt::print("{}\n", iota_scan(5, flux::cmp::max));   // ✅ [1, 2, 3, 4, 5]
    fmt::print("{}\n", iota_scan(5, flux::cmp::min));   // ✅ [1, 1, 1, 1, 1]
}
```

https://flux.godbolt.org/z/qqYs3vPvT

The reason for the two functions is that I wanted consistency with `fold()` and `fold_first()`, the latter of which also doesn't use an initial value. It's mentioned in [the documentation](https://tristanbrindle.com/flux/reference/adaptors.html#scan) but maybe I need to make the difference more clear somehow!

I hope this explains it!

(Also, FYI, you can now select Flux in the "Libraries" tab in Compiler Explorer, so you don't need to do the `#include <really_long_path_to_github>` thing any more.)

**Comment by codereport** [comment]
Ah, that makes sense. I just need `scan_first` then! Thanks 🙏
