### ISSUE TITLE
Vcpkg package is out of date

### ISSUE THREAD

**Issue by tcbrindle** [tcbrindle/flux#206]
Both the [Conan](https://conan.io/center/recipes/flux) and [Vcpkg](https://vcpkg.io/en/package/flux) Flux packages are git snapshots from some time ago. 

It would be great to get these updated for the new Flux release.

**EDIT** Conan now has [Flux 0.4.0](https://conan.io/center/recipes/flux?version=0.4.0), thanks @SidneyCogdill

**Comment by tcbrindle** [comment]
(I guess this is only a "good first issue" if you're already familiar with Conor or Vcpkg, but...)

**Comment by Sid911** [comment]
@tcbrindle Hi, I am also trying to get newer version of flux to xrepo (atleast for time being my own xrepo then to official one). I do have a question. Will the tags be now kept as is? I can't find release tags before 0.4.0. The previous version for xrepo is for commit 8434e8e0fd131cebc3aed0d845530335bf7fb5e1 tagged 2023.08.17 which is similar to vcpkg and connan which have the clang 18 crash issue present. 

If the tags releases will be kept as, is it would be easier to write versions.

**Comment by tcbrindle** [comment]
Hi @Sid911,

> Will the tags be now kept as is? I can't find release tags before 0.4.0

Yes, the tags will be kept as-is from now on. Future releases of Flux will use semantic versioning, tagged appropriately. (0.4.0 was the first "official" numbered release).

I hope this helps, thanks for helping to get Flux packaged

**Comment by SidneyCogdill** [comment]
For conan it appears only minimal efforts are required to the [recipes](https://github.com/conan-io/conan-center-index/tree/master/recipes/flux):

`config.yml`:

```diff
  versions:
+  "0.4.0":
+    folder: all
    "cci.20240115":
      folder: all
```

`all/conandata.yml`:

```diff
   sources:
+   "0.4.0":
+     url: "https://codeload.github.com/tcbrindle/flux/zip/43c09af5cc2e89e32b98ddc3507247f593ec2642"
+     sha256: "9d8891b2ab9f826b301678b17011d48ab6c85e534e065f66269ae08537be68d5"
    "cci.20240115":
      url: "https://codeload.github.com/tcbrindle/flux/zip/e942a678ed3b46c7f7ffeebe47eed5c5bec005b2"
      sha256: "3832fb160417d14cfb3636c8edab04b2d0cd6c230b4d474a18bb1389fa1c3b8f"
```

I've tried this on my local system and it builds correctly and flux works. Need someone to submit that to conan center index. Who's maintaining flux package for conan?

**Comment by SidneyCogdill** [comment]
ping @valgur ([original PR](https://github.com/conan-io/conan-center-index/pull/22401))

**Comment by tcbrindle** [comment]
The Conan update looks like it has propagated through (https://conan.io/center/recipes/flux?version=0.4.0), thanks very much @SidneyCogdill!

**Comment by SidneyCogdill** [comment]
Conan Center current has some issues that can cause users to miss v0.4.0: https://github.com/conan-io/conan-center-index/issues/25863#issuecomment-2461921683

Therefore it might be helpful to directly mention conan tutorials in `README.md`:

```sh
conan remote update --url https://center2.conan.io conancenter
```

```
[requires]
flux/0.4.0
[generators]
CMakeDeps
CMakeToolchain
[layout]
cmake_layout
```

and warn that `flux/[*]` wildcard will miss the latest version due to the `cci` name.

and also add a direct link to the latest version https://conan.io/center/recipes/flux?version=0.4.0

**Comment by tcbrindle** [comment]
The vcpkg package has now been updated as well, thanks again @SidneyCogdill!
