### ISSUE TITLE
Use low-level contiguous_sequence optimisations where appropriate

### ISSUE THREAD

**Issue by tcbrindle** [tcbrindle/flux#57]
Currently we [optimise `output_to()`](https://github.com/tcbrindle/flux/blob/main/include/flux/op/output_to.hpp#L35) for `contiguous_sequence`s of trivial types to use `std::memmove`.

There are more places where we could use equivalent low-level optimisations, including

 * [ ] `fill()` (using `memset()`)
 * [ ] `equal()` (using `memcmp()`)
 * [ ] `compare()` (using `memcmp()`)
 * [ ] `find()` (using `memchr()`)
 * [x] ~~`search()` (using `memmem()` where available)~~

See also the [equivalent bug for Nanorange](https://github.com/tcbrindle/NanoRange/issues/107) with more information about when these optimisations can be used.

**Comment by DeveloperPaul123** [comment]
I've started work on this in #103

**Comment by DeveloperPaul123** [comment]
@tcbrindle I have a question while working on `equal()`

There is this test case:

```cpp
 // Different but comparable element types
{
    int arr1[] = {1, 2, 3, 4, 5};
    float arr2[] = {1.f, 2.f, 3.f, 4.f, 5.f};

    STATIC_CHECK(flux::equal(arr1, arr2));
}
```

It seems that the intension is to compare values and accept them as equal. If we want to optimize with `std::memcmp`, does it seem reasonable to require the the values of the 2 sequences be of the same type? Currently, using the `std::memcmp` optimization causes the above test to fail (where it previously passed).

**Comment by DeveloperPaul123** [comment]
@tcbrindle Currently, `std::memmem` is a GNU extension. Is it desirable to use this on platforms that's it's available on? Currently C++ extensions are explicitly turned off via CMake

**Comment by tcbrindle** [comment]
@DeveloperPaul123 Thinking about it some more, I think it's probably better to not use `memmem` for now and stick with portable standard library facilities... we can look at platform/vendor-specific optimisations later if/when they're needed.

**Comment by tcbrindle** [comment]
Added in #103, thanks @DeveloperPaul123!
