### ISSUE TITLE
Odd location of `iota`

### ISSUE THREAD

**Issue by brycelelbach** [tcbrindle/flux#90]
Why is `iota` hidden in `<flux/source/*>`? Other views are in `<flux/op/*>`.

**Comment by tcbrindle** [comment]
The types in the `source` directory are "sequence factories" -- things that (only) go at the start of a Flux pipeline, that is, the "source" of some data. `iota` is one of those, along with things like `from_range`, `single`, `empty`, `istream` etc.

The `op` directory is for adaptors (things that go in the middle of a pipeline and return a lazily evaluated sequence, like `filter`, `map` or `chunk`) and for algorithms (things that go at the end of a pipeline and either return a value or modify a sequence in-place, like `sum`, `fold` or `sort`).

Admittedly this distinction is fairly arbitrary, but hopefully that makes sense!
